### ISSUE TITLE
Recipe Tags Display Format

### ISSUE THREAD

**Issue by Renzo-codespace** [CodeSpace-Academy/ASE_2023_GROUP_A#1]
### SCENARIO: 
  
  - Tags are displayed in a consistent format
    
    ### GIVEN: 
    
    - I am viewing the list of recipe previews
    
    ### WHEN: 
    
    - I navigate to a specific recipe page
    
    ### THEN: 
    
    - The recipe tags should be displayed in a consistent, readable format

**Comment by Mpho-vincent-makgwe** [comment]
tags displays in bullet forrm

**Comment by Renzo-codespace** [comment]
The solution for this needs to be merged into the main branch before it can closed.
