### ISSUE TITLE
Recipe Details Formatting

### ISSUE THREAD

**Issue by Renzo-codespace** [CodeSpace-Academy/ASE_2023_GROUP_A#10]
### SCENARIO: 
  
  - Recipe details are properly formatted
    
    ### GIVEN: 
    
    - I am viewing the list of recipe previews
    
    ### WHEN: 
    
    - I navigate to a specific recipe page
    
    ### THEN: 
    
    - The recipe details should be properly formatted with paragraphs, bullet points, and other appropriate styling as necessary

**Comment by Mpho-vincent-makgwe** [comment]
The format is correctly formated

**Comment by Renzo-codespace** [comment]
The solution for this needs to be merged into the main branch before it can closed.

**Comment by Renzo-codespace** [comment]
https://cooking-devs.vercel.app/Almond%20Fudge%20Banana%20Cake

Cannot see recipe title.
"servings" does not show any meaningful information.
the first ingredient shows text that isn't meaningful.
The instructions are formatted in a way that is hard to read.
