### ISSUE TITLE
Displaying message for no matching recipes

### ISSUE THREAD

**Issue by Renzo-codespace** [CodeSpace-Academy/ASE_2023_GROUP_A#117]
### Scenario: 
  
  - Recipes list shows a message when no recipes match the selected category
    
    ### Given: 
    
    - I have selected a specific category from the category filter
    
    ### When: 
    
    - The filter is applied
    - **AND** no recipes match the selected category
    
    ### Then: 
    
    - The recipes list should show a message indicating no recipes were found

**Comment by Renzo-codespace** [comment]
The solution to this issue must be demonstrated before it can be considered as done.

**Comment by olgamaseng** [comment]
Displaying message for no matching recipes #117
