### ISSUE TITLE
Displaying total time

### ISSUE THREAD

**Issue by Renzo-codespace** [CodeSpace-Academy/ASE_2023_GROUP_A#15]
### SCENARIO: 
  
  - Recipe preview shows total time
    
    ### GIVEN: 
    
    - I am viewing a recipe preview
    
    ### WHEN: 
    
    - I look at the displayed times
    
    ### THEN: 
    
    - I should also see the total time, calculated by adding the preparation and cooking times together

**Comment by Mpho-vincent-makgwe** [comment]
Total time is displayed correctly for all recipes

**Comment by Renzo-codespace** [comment]
The solution for this needs to be merged into the main branch before it can closed.

**Comment by Renzo-codespace** [comment]
Recipe Previews must the total time required.
