### ISSUE TITLE
Distinguishing prep and cooking time

### ISSUE THREAD

**Issue by Renzo-codespace** [CodeSpace-Academy/ASE_2023_GROUP_A#16]
### SCENARIO: 
  
  - Preparation and cooking time are clearly distinguished
    
    ### GIVEN: 
    
    - I am viewing the preparation and cooking time on a recipe preview
    
    ### WHEN: 
    
    - I look at the displayed times
    
    ### THEN: 
    
    - The preparation and cooking times should be clearly labelled and distinguished

**Comment by Mpho-vincent-makgwe** [comment]
prep time and cook time are all correctly distinguished.
