### ISSUE TITLE
Displaying prep and cooking time

### ISSUE THREAD

**Issue by Renzo-codespace** [CodeSpace-Academy/ASE_2023_GROUP_A#17]
### SCENARIO: 
  
  - User sees the preparation and cooking time on the recipe preview
    
    ### GIVEN: 
    
    - I am browsing recipes in the recipe app
    
    ### WHEN: 
    
    - I view a recipe preview
    
    ### THEN: 
    
    - I should see the estimated preparation and cooking time

**Comment by Mpho-vincent-makgwe** [comment]
both prep and cooking time are displayed

**Comment by Renzo-codespace** [comment]
The solution for this needs to be merged into the main branch before it can closed.
