### ISSUE TITLE
Loading 100 recipes

### ISSUE THREAD

**Issue by Renzo-codespace** [CodeSpace-Academy/ASE_2023_GROUP_A#19]
### SCENARIO: 
  
  - User sees 100 recipes when first entering the recipes list page
    
    ### GIVEN: 
    
    - I am on the recipes list page
    
    ### WHEN: 
    
    - The page has loaded
    
    ### THEN: 
    
    - I should see the first 100 recipes

**Comment by Cbazil** [comment]
@Mpho-vincent-makgwe to finalize the mongodb connection

**Comment by Mpho-vincent-makgwe** [comment]
fetched all recipes from mongo db, and loaded only 100 on the initial page.

**Comment by Renzo-codespace** [comment]
The solution for this needs to be merged into the main branch before it can closed.
