### ISSUE TITLE
Mobile view of recipe list

### ISSUE THREAD

**Issue by Renzo-codespace** [CodeSpace-Academy/ASE_2023_GROUP_A#26]
### SCENARIO: 
  
  - Ensure recipe list is displayed correctly on mobile view
    
    ### GIVEN: 
    
    - I am a user accessing the recipe app on a mobile browser
    
    ### WHEN: 
    
    - I navigate to the recipe list page
    
    ### THEN: 
    
    - The recipe list should be displayed in a single-column list view 
    - **AND** I should be able to scroll vertically through the recipes

**Comment by Mpho-vincent-makgwe** [comment]
mobile view is in single colomn

**Comment by Renzo-codespace** [comment]
The solution for this needs to be merged into the main branch before it can closed.
