### ISSUE TITLE
Desktop view of recipe list

### ISSUE THREAD

**Issue by Renzo-codespace** [CodeSpace-Academy/ASE_2023_GROUP_A#27]
### SCENARIO: 
  
  - Ensure recipe list is displayed correctly on desktop view
    
    ### GIVEN: 
    
    - I am a user accessing the recipe app on a desktop browser
    
    ### WHEN: 
    
    - I navigate to the recipe list page
    
    ### THEN: 
    
    - The recipe list should be displayed in a grid view 
    - **AND** I should be able to view multiple recipes side by side

**Comment by Mpho-vincent-makgwe** [comment]
Deskop view is displaying side by side

**Comment by Renzo-codespace** [comment]
The solution for this needs to be merged into the main branch before it can closed.
