### ISSUE TITLE
Configure MongoDB JS with .env file

### ISSUE THREAD

**Issue by Renzo-codespace** [CodeSpace-Academy/ASE_2023_GROUP_A#28]
### SCENARIO: 
  
  - Configure the MongoDB JS library using an .env file
    
    ### GIVEN: 
    
    - I have installed the MongoDB JS library
    - **AND** I have an .env file with the required variables
    
    ### WHEN: 
    
    - I initialize MongoDB in the project using the required variables from the .env file
    
    ### THEN: 
    
    - The MongoDB client should be correctly initialized and ready to use

**Comment by Mpho-vincent-makgwe** [comment]
mongoDB is correctly connected using next.config for phase checking and setting env code

**Comment by Renzo-codespace** [comment]
The solution for this needs to be merged into the main branch before it can closed.
