### ISSUE TITLE
Display All Tags Associated with a Recipe

### ISSUE THREAD

**Issue by Renzo-codespace** [CodeSpace-Academy/ASE_2023_GROUP_A#3]
### SCENARIO: 
  
  - All tags displayed for an existing recipe
    
    ### GIVEN: 
    
    - I am viewing the list of recipe previews
    
    ### WHEN: 
    
    - I navigate to a specific recipe page
    
    ### THEN: 
    
    - I should see all the tags associated with the recipe

**Comment by Mpho-vincent-makgwe** [comment]
all tags associated with a recipe are displayed under that recipe

**Comment by Renzo-codespace** [comment]
The solution for this needs to be merged into the main branch before it can closed.

**Comment by Renzo-codespace** [comment]
Recipe tags must be visible as soon as the details page loads.
